VirtualDispatcherWebsite/VirtualDispatcherWebsite/Models/CreateLoadSheetViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace VirtualDispatcherWebsite.Models
{
    public class CreateLoadSheetViewModel
    {
        // weight on getAircraftByRegistration
        [Required]
        public double APSWeight { get; set; }

        public bool Observer1 { get; set; }

        public bool Observer2 { get; set; }

        public bool Attendance5 { get; set; }

        public bool Attendance6 { get; set; }
        [Required]
        public string MaxTakeOffWeight { get; set; } //todo : decimal

        // maxZfw on getAircraftByRegistration
        [Required]
        public int MaxZeroFuelWeight { get; set; }

        // maxLw on getAircraftByRegistration
        [Required]
        public int MaxLandingWeight { get; set; }
        [Required]
        public decimal CockpitCrewWeight { get; set; }
        [Required]
        public decimal CabinCrewWeight { get; set; }
        [Required]
        public string FlightNumber { get; set; }
        [Required]
        // pilot
        public int RampFuel { get; set; }
        [Required]
        //pilot
        public int TaxiFuel { get; set; }
        [Required]
        // pilot
        public int TripFuel { get; set; }
        [Required]
        public int MaxTakeOffWeightCaptain{ get; set; }
        [Required]
        public int Adults { get; set; }
        [Required]
        public int Childs { get; set; }
        [Required]
        public int Infant { get; set; }
        [Required]
        public int PaxForward { get; set; }
        [Required]
        public int PaxMiddle { get; set; }
        [Required]
        public int PaxAfter { get; set; }
        [Required]
        public int BagsHold1 { get; set; }
        [Required]
        public int BagsHold2 { get; set; }
        [Required]
        public int BagsHold3 { get; set; }
        [Required]
        public int BagsHold4 { get; set; }
        [Required]
        public decimal CargoHold1Weight { get; set; }
        [Required]
        public decimal CargoHold2Weight { get; set; }
        [Required]
        public decimal CargoHold3Weight { get; set; }
        [Required]
        public decimal CargoHold4Weight { get; set; }
        [Required]
        public string AircraftRegistrationNumber { get; set; }
    }
}

VirtualDispatcherWebsite/VirtualDispatcherWebsite/Models/LoadSheetResultsViewModel.cs
using System;
using VirtualDispatcher.Core;

namespace VirtualDispatcherWebsite.Models
{
    public class LoadSheetResultsViewModel
    {
        public int AdultNumber { get; internal set; }
        public double AllowedTrafficLoad { get; internal set; }
        public double AllowedWeightForTow { get; internal set; }
        public int BagsHold1 { get; internal set; }
        public double BagsHold1Weight { get; internal set; }
        public int BagsHold2 { get; internal set; }
        public double BagsHold2Weight { get; internal set; }
        public int BagsHold3 { get; internal set; }
        public double BagsHold3Weight { get; internal set; }
        public int BagsHold4 { get; internal set; }
        public double BagsHold4Weight { get; internal set; }
        public int ChildNumber { get; internal set; }
        public double DryOperatingWeight { get; internal set; }
        public int FreeGateBagsTrimAdjustement { get; internal set; }
        public int Landing { get; internal set; }
        public double Load { get; internal set; }
        public double MaxPlacardWeight { get; internal set; }
        public double OperatingWeight { get; internal set; }
        public int Pax { get; internal set; }
        public int PaxAfter { get; internal set; }
        public double PaxAfterWeight { get; internal set; }
        public int PaxForward { get; internal set; }
        public double PaxForwardWeight { get; internal set; }
        public int PaxMiddle { get; internal set; }
        public double PaxMiddleWeight { get; internal set; }
        public double TakeOffFuel { get; internal set; }
        public double Tow { get; internal set; }
        public double UncorrectLoad { get; internal set; }
        public double ZeroFuel { get; internal set; }
        public double ZeroFuelWeight { get; internal set; }
        //public FlightRoute flightRoute { get; set; }
        //public FleetWeightRegistrationData {get; set;}
    }
}

VirtualDispatcherWebsite/VirtualDispatcherWebsite/Controllers/CreateLoadSheetController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using VirtualDispatcherWebsite.Models;
using VirtualDispatcher.Service;

namespace VirtualDispatcherWebsite.Controllers
{
    public class CreateLoadSheetController : Controller
    {
        private LoadSheetRepository loadSheetRepository = new LoadSheetRepository();
        private IFlightRouteService _flightRouteService;
        private ILoadSheetBagWeightService _loadsheetBagWeightService;
        private IPassengerWeightService _passengerWeightService;
        private IGetFleetWeightByRegistrationService _getFleetWeightByRegistrationNumber;

        public CreateLoadSheetController(IFlightRouteService flightRouteService, ILoadSheetBagWeightService loadsheetBagWeightService,
            IPassengerWeightService passengerWeightService,
            IGetFleetWeightByRegistrationService getFleetWeightByRegistrationService)
        {
            _flightRouteService = flightRouteService;
            _loadsheetBagWeightService = loadsheetBagWeightService;
            _passengerWeightService = passengerWeightService;
            _getFleetWeightByRegistrationNumber = getFleetWeightByRegistrationService;
        }

        // GET: CreateLoadSheet
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(CreateLoadSheetViewModel createLoadScheetModel)
        {
            // add server controls
            return RedirectToAction("LoadSheetResults", createLoadScheetModel);
            
        }

        public ActionResult LoadSheetResults(CreateLoadSheetViewModel createLoadScheetModel)
        {
            var flightRoute = _flightRouteService.Execute(createLoadScheetModel.FlightNumber);

            var fleetWeightData = _getFleetWeightByRegistrationNumber.Execute(createLoadScheetModel.AircraftRegistrationNumber);

            var loadSheetResultViewModel = new LoadSheetResultsViewModel();

            loadSheetResultViewModel.DryOperatingWeight = fleetWeightData.Weight +
                (createLoadScheetModel.Observer1 ? 90.1 : 0) +
                (createLoadScheetModel.Observer2 ? 90.1 : 0) +
                (createLoadScheetModel.Attendance5 ? 79.9 : 0) +
                (createLoadScheetModel.Attendance6 ? 79.9 : 0);

            loadSheetResultViewModel.TakeOffFuel = createLoadScheetModel.RampFuel - createLoadScheetModel.TaxiFuel; //TODO: aggiustare le ultime due cifre
            loadSheetResultViewModel.OperatingWeight = loadSheetResultViewModel.DryOperatingWeight + loadSheetResultViewModel.TakeOffFuel;
            if (loadSheetResultViewModel.OperatingWeight <= 66990)
            {
                loadSheetResultViewModel.MaxPlacardWeight = 66990;
            }else if(loadSheetResultViewModel.OperatingWeight <= 69990)
            {
                loadSheetResultViewModel.MaxPlacardWeight = 69990;
            }else
            {
                loadSheetResultViewModel.MaxPlacardWeight = 74990;
            }
            loadSheetResultViewModel.Landing = fleetWeightData.FleetWeight.MaxLW + createLoadScheetModel.TripFuel;
            loadSheetResultViewModel.ZeroFuel = fleetWeightData.FleetWeight.MaxZFW + loadSheetResultViewModel.TakeOffFuel;
            loadSheetResultViewModel.AllowedWeightForTow = Math.Min(Math.Min(loadSheetResultViewModel.ZeroFuel, loadSheetResultViewModel.MaxPlacardWeight), loadSheetResultViewModel.Landing);
            loadSheetResultViewModel.AllowedTrafficLoad = loadSheetResultViewModel.AllowedWeightForTow - loadSheetResultViewModel.OperatingWeight;
            loadSheetResultViewModel.Pax = createLoadScheetModel.Adults + createLoadScheetModel.Childs;
            loadSheetResultViewModel.AdultNumber = createLoadScheetModel.Adults;
            loadSheetResultViewModel.ChildNumber = createLoadScheetModel.Childs;
            loadSheetResultViewModel.PaxForward = createLoadScheetModel.PaxForward;
            loadSheetResultViewModel.PaxMiddle = createLoadScheetModel.PaxMiddle;
            loadSheetResultViewModel.PaxAfter = createLoadScheetModel.PaxAfter;
            loadSheetResultViewModel.PaxForwardWeight = this._passengerWeightService.Execute(0, createLoadScheetModel.PaxForward).Weight;
            loadSheetResultViewModel.PaxMiddleWeight = this._passengerWeightService.Execute(1, createLoadScheetModel.PaxMiddle).Weight;
            loadSheetResultViewModel.PaxAfterWeight = this._passengerWeightService.Execute(2, createLoadScheetModel.PaxAfter).Weight;
            loadSheetResultViewModel.BagsHold1 = createLoadScheetModel.BagsHold1;
            loadSheetResultViewModel.BagsHold1Weight = this._loadsheetBagWeightService.Execute(1,createLoadScheetModel.BagsHold1).Weight;
            loadSheetResultViewModel.BagsHold2 = createLoadScheetModel.BagsHold2;
            loadSheetResultViewModel.BagsHold2Weight = this._loadsheetBagWeightService.Execute(2, createLoadScheetModel.BagsHold2).Weight;
            loadSheetResultViewModel.BagsHold3 = createLoadScheetModel.BagsHold3;
            loadSheetResultViewModel.BagsHold3Weight = this._loadsheetBagWeightService.Execute(3, createLoadScheetModel.BagsHold3).Weight;
            //loadSheetResultViewModel.BagsHold4 = createLoadScheetModel.BagsHold4;
            //loadSheetResultViewModel.BagsHold4Weight = this._loadsheetBagWeightService.Execute(4, createLoadScheetModel.BagsHold4).Weight;
            loadSheetResultViewModel.FreeGateBagsTrimAdjustement = 0; // TODO
            loadSheetResultViewModel.UncorrectLoad = loadSheetResultViewModel.PaxForwardWeight
                + loadSheetResultViewModel.PaxMiddleWeight
                + loadSheetResultViewModel.PaxAfterWeight
                + loadSheetResultViewModel.BagsHold1Weight
                + loadSheetResultViewModel.BagsHold2Weight
                + loadSheetResultViewModel.BagsHold3Weight
                + loadSheetResultViewModel.BagsHold4Weight
                + loadSheetResultViewModel.FreeGateBagsTrimAdjustement;

            loadSheetResultViewModel.Load = loadSheetResultViewModel.UncorrectLoad - loadSheetRepository.getChildAdjustment(createLoadScheetModel.Childs);
            if(loadSheetResultViewModel.Load <= loadSheetResultViewModel.AllowedTrafficLoad)
            {
                return View("Error");
            }
            loadSheetResultViewModel.ZeroFuelWeight = loadSheetResultViewModel.Load + loadSheetResultViewModel.DryOperatingWeight;
            loadSheetResultViewModel.Tow = loadSheetResultViewModel.ZeroFuelWeight + loadSheetResultViewModel.TakeOffFuel;
            return View(loadSheetResultViewModel);
        }


    }
}

VirtualDispatcherWebsite/VirtualDispatcherWebsite/Views/CreateLoadSheet/Index.cshtml
@using VirtualDispatcherWebsite.Models
@model CreateLoadSheetViewModel
@{
    ViewBag.Title = "Create LoadSheet";
}
<h2>@ViewBag.Title.</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loadSheetForm">
            @using (Html.BeginForm("Index", "CreateLoadSheet", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, null, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <h4></h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(m => m.AircraftRegistrationNumber, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.AircraftRegistrationNumber, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.AircraftRegistrationNumber, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.APSWeight, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.APSWeight, new { @class = "form-control", @readonly = "readonly" })
                        @Html.ValidationMessageFor(m => m.APSWeight, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Observer1, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.CheckBoxFor(m => m.Observer1, new { @class = "form-control", @readonly = "readonly" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Observer2, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.CheckBoxFor(m => m.Observer2, new { @class = "form-control", @readonly = "readonly" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Attendance5, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.CheckBoxFor(m => m.Attendance5, new { @class = "form-control", @readonly = "readonly" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Attendance6, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.CheckBoxFor(m => m.Attendance6, new { @class = "form-control", @readonly = "readonly" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.MaxTakeOffWeight, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.MaxTakeOffWeight, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.MaxTakeOffWeight, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.MaxZeroFuelWeight, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.MaxZeroFuelWeight, new { @class = "form-control", @readonly = "readonly" })
                        @Html.ValidationMessageFor(m => m.MaxZeroFuelWeight, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.MaxLandingWeight, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.MaxLandingWeight, new { @class = "form-control", @readonly = "readonly" })
                        @Html.ValidationMessageFor(m => m.MaxLandingWeight, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.FlightNumber, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.FlightNumber, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.FlightNumber, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.CockpitCrewWeight, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.CockpitCrewWeight, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.CockpitCrewWeight, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.CabinCrewWeight, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.CabinCrewWeight, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.CabinCrewWeight, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.RampFuel, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.RampFuel, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.RampFuel, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.TaxiFuel, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.TaxiFuel, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.TaxiFuel, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.TripFuel, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.TripFuel, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.TripFuel, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.MaxTakeOffWeightCaptain, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.MaxTakeOffWeightCaptain, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.MaxTakeOffWeightCaptain, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Adults, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Adults, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Adults, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Childs, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Childs, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Childs, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Infant, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Infant, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Infant, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.PaxForward, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.PaxForward, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.PaxForward, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.PaxMiddle, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.PaxMiddle, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.PaxMiddle, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.PaxAfter, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.PaxAfter, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.PaxAfter, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.BagsHold1, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.BagsHold1, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.BagsHold1, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.BagsHold2, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.BagsHold2, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.BagsHold2, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.BagsHold3, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.BagsHold3, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.BagsHold3, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.BagsHold4, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.BagsHold4, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.BagsHold4, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.CargoHold1Weight, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.CargoHold1Weight, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.CargoHold1Weight, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.CargoHold2Weight, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.CargoHold2Weight, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.CargoHold2Weight, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.CargoHold3Weight, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.CargoHold3Weight, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.CargoHold3Weight, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.CargoHold4Weight, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.CargoHold4Weight, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.CargoHold4Weight, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Calculate" class="btn btn-default" />
                    </div>
                </div>
            }
        </section>
    </div>
</div>

VirtualDispatcherWebsite/VirtualDispatcherWebsite/Views/CreateLoadSheet/LoadSheetResults.cshtml
@using System.Reflection
@using Newtonsoft.Json;
@model LoadSheetResultsViewModel

@{
    ViewBag.Title = "LoadSheetResults";
}

<h2>LoadSheetResults</h2>

@{
    Type tModelType = Model.GetType();
    PropertyInfo[] arrayPropertyInfos = tModelType.GetProperties();

    foreach (PropertyInfo property in arrayPropertyInfos)
    {
        <a>@property.Name : <strong>@property.GetValue(Model).ToString()</strong></a><br />
    }

}